db:
    image: postgres:9.1.22
    container_name: postgres-container
    ports:
        - "5432:5432"
    environment:
        POSTGRES_USER: 'postgres'
        POSTGRES_PASSWORD: 'postgres'

server:
    build: .
    container_name: wildfly-container
    links:
      - db:db
    ports:
        - "80:8080"

hub:
    image: selenium/hub:2.53.0
    container_name: hub-container
    ports:
      - "4444:4444"

firefox:
    image: selenium/node-firefox:2.53.0
    container_name: firefox-container
    ports:
      - "5900:5900"
    links:
      - hub:hub
      - server:server
